apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: workshop
  name: heikkihei-basic-node
  labels:
    app: heikkihei-basic-node

spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: heikkihei-basic-node

  template:
    metadata:
      labels:
        app: heikkihei-basic-node
      annotations:
    spec:
      containers:
        - image: gcr.io/unity-ads-workshop-test/heikkihei-basic-node:latest
          name: heikkihei-basic-node
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 0.1
              memory: 128Mi
            limits:
              cpu: 0.5
              memory: 1024Mi

      nodeSelector:
        service: workshop