kind: Service
apiVersion: v1
metadata:
  labels:
    app: heikki-hei-basic-node
  name: heikki-hei-basic-node 
  namespace: workshop

spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: heikki-hei-basic-node