kind: Service
apiVersion: v1
metadata:
  labels:
    app: heikkihei-basic-node
  name: heikkihei-basic-node
  namespace: workshop

spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: heikkihei-basic-node